### ISSUE TITLE
please update "Soartex_Fanver”  to 1.16

### ISSUE THREAD

**Issue by SunShineJF** [InvictusGraphics/Invictus_Textures#8]
please update the Textures, "Soartex_Fanver”,  to 1.16，this textures is the best one of that I used.
There are problems with evey kinds of walls in the 1.16 minecraft version.
![QQ截图20200705192943](https://user-images.githubusercontent.com/49141302/86531789-e0256200-bef6-11ea-8648-e490a86a7210.png)
![QQ截图20200705192921](https://user-images.githubusercontent.com/49141302/86531790-e1568f00-bef6-11ea-940e-803ebafdedde.png)

**Comment by mquinnv** [comment]
yeah, wish i knew how to help. minecraft sucks without invictus :-)

**Comment by Shoeboxam** [comment]
I pushed a port to 1.16 and released 6.0.0. The new textures have not been made, but all the old stuff should work. Please open more issues if you find bugs. Thanks!

**Comment by mquinnv** [comment]
fantastic. i had hacked something together that was mostly working, but i'm sure this will be a better base

**Comment by Shoeboxam** [comment]
Be sure to open issues for any bugs you see. Thanks!
